import Header from "../components/General/Header"
import Head from 'next/head'
const about = () => {
  return (
    <div>
    <Head>
      <title>WiseWomanBirthServices</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
        <Header /> 
    </main>
  </div>
  )
}

export default about