import Head from "next/head";
import Header from "../components/General/Header";
//Home page/landing page
export default function Home() {
  return (
    <div>
      <Head>
        <title>WiseWomanBirthServices</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
      </main>
    </div>
  );
}
