import Head from "next/head";
import Header from "../components/General/Header";
import { Landing } from "../components/Home/Landing";
import Image from "next/image";
import BabyFeet from "../public/BabyFeet.jpg";
import s from "../styles/Home/Home.module.css";
import { ContactBtn } from "../components/Home/ContactBtn";
//Home page/landing page
export default function Home() {
  return (
    <div>
      <Head>
        <title>WiseWomanBirthServices: Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <div className={s.container}>
          <div className={s.headerContainer}>
            <Header />
          </div>
          <div className={s.imgContainer}>
            <div className={s.img}></div>
          </div>
        </div>
        <Landing />
        <ContactBtn />
      </main>
      <div className={s.crContainer}>
        <h3>© 2023 Wise Woman Birth Services. All Rights Reserved.</h3>
      </div>
    </div>
  );
}
