import Header from "../components/General/Header";
import Head from "next/head";
import Landing from "../components/Services/Landing";
import s from "../styles/Services/Services.module.css";
import BirthServicesCard from "../components/Services/BirthServicesCard";
import PostPartumCareCard from "../components/Services/PostPartumCareCard";
const services = () => {
  return (
    <div>
      <Head>
        <title>WiseWomanBirthServices: Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <div className={s.container}>
          <div className={s.headerContainer}>
            <Header />
          </div>
          <div className={s.imgContainer}>
            <div className={s.img}></div>
          </div>
        </div>
        <Landing />
        <BirthServicesCard />
        <PostPartumCareCard />
      </main>
    </div>
  );
};

export default services;
